[package]
name = "luajit-bytekude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
bstr = "0.2.17"
deku = { version = "0.13.1" }
